POST {{addr}}/web/v1/NewRole
Content-Type: application/json
Authorization: BEARER {{admin_token}}

{
  "role_name": "1x"
}

###
POST {{addr}}/web/v1/UpdateRole
Content-Type: application/json
Authorization: BEARER {{admin_token}}

{
  "role_id": 2,
  "role_name": "x1",
  "delete": true
}

###
GET {{addr}}/web/v1/QueryRole?role_id=11
Authorization: BEARER {{admin_token}}

###
GET {{addr}}/web/v1/GetRoleList
Authorization: BEARER {{admin_token}}
