app_adminbg:
  # dev开发环境 test测试环境 prod线上环境
  name: "adminbg"  # 服务名称
  mode: "dev"
  host: "0.0.0.0"
  port: 6500
  read_timeout: 1
  write_timeout: 2

logger:
  # 日志存放路径（win/unix不同）
  dir: D:/tmp/adminbg/log
  db_log_filename: "db.log"
  req_log_filename: "req.log"
  default_log_filename: "default.log"
  # 控制台日志
  to_stdout: true

jwt:
  # token 密钥，生产环境时及的修改
  secret: "this is a jwt secret"
  # token 过期时间 单位：秒
  timeout: 3600
  # 用于接口测试，若req携带token则会覆盖这个 生产环境不读取
  test_token: ".jx"

database:
  mysql:
    source: root:123456@tcp(192.168.1.168:3306)/buying?charset=utf8&parseTime=True&loc=Local&timeout=1000ms